# Generated by Django 5.0.14 on 2026-02-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
                ("pickup_point", models.CharField(max_length=255)),
                ("destination", models.TextField()),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
                "db_table": "deliveries",
            },
        ),
    ]
