# Generated by Django 5.0.14 on 2026-08-20 20:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "logistics",
            "0003_alter_delivery_options_remove_delivery_destination_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="confirmation_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="delivery",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="delivery",
            name="confirmation_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
