# Generated by Django 5.0.14 on 2026-07-02 15:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_latitude_user_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="newsletter_opt_in",
            field=models.BooleanField(default=True),
        ),
    ]
