# Generated by Django 5.0.14 on 2026-07-05 17:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_email_user_newsletter_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="location_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
