# Generated by Django 5.0.14 on 2026-07-09 12:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_available_user_location_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="courier_application_status",
            field=models.CharField(
                choices=[
                    ("none", "Aucune demande"),
                    ("pending", "En attente de validation"),
                    ("approved", "Approuvée"),
                    ("rejected", "Refusée"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
