# Generated by Django 5.0.14 on 2026-07-10 12:41
from django.db import migrations
from django.db import models


def blank_emails_to_null(apps, schema_editor):
    """
    Nécessaire avant d'ajouter la contrainte unique plus bas : plusieurs comptes avec
    email="" (chaîne vide) violeraient l'unicité entre eux, alors que plusieurs NULL sont
    autorisés par une contrainte unique SQL standard.
    """
    User = apps.get_model("users", "User")
    User.objects.filter(email="").update(email=None)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_courier_application_status"),
    ]

    operations = [
        # 1) Rendre la colonne nullable D'ABORD (sans unique pour l'instant) : la donnée doit
        #    pouvoir accepter NULL avant que blank_emails_to_null n'y écrive des NULL, sinon
        #    l'UPDATE viole encore l'ancienne contrainte NOT NULL.
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        # 2) Nettoyer la donnée existante ("" -> NULL) maintenant que c'est possible.
        migrations.RunPython(blank_emails_to_null, migrations.RunPython.noop),
        # 3) Ajouter la contrainte unique une fois les doublons de "" éliminés.
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
