# Generated by Django 5.0.14 on 2026-08-20 20:53
import cloudinary.models
from django.db import migrations
from django.db import models

import common.images.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="courier_id_document",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Pièce d'identité pour la candidature coursier. Stockée sur Cloudinary en accès restreint (non public).",
                max_length=255,
                null=True,
                validators=[
                    common.images.validators.ImageFileValidator(max_bytes=5242880)
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="courier_vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[("moto", "Moto"), ("velo", "Vélo"), ("voiture", "Voiture")],
                max_length=10,
            ),
        ),
    ]
