# Generated by Django 5.0.14 on 2026-08-23 16:14
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_joboffer_company_jobofferfavorite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TalentProfile",
        ),
    ]
