# Generated by Django 5.0.14 on 2026-08-20 20:53
import cloudinary.models
from django.db import migrations

import common.images.validators


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_listing_company_listingfavorite_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    common.images.validators.ImageFileValidator(max_bytes=2097152)
                ],
            ),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                validators=[
                    common.images.validators.ImageFileValidator(max_bytes=5242880)
                ],
            ),
        ),
    ]
