# Generated by Django 5.0.14 on 2026-08-20 20:53
import cloudinary.models
from django.db import migrations

import common.images.validators


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    common.images.validators.ImageFileValidator(max_bytes=2097152)
                ],
            ),
        ),
    ]
