"""
Django settings for back_sentaa project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "sentaaback.onrender.com,localhost").split(
    ","
)


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "channels",
    "django.contrib.staticfiles",
    "phonenumber_field",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "rest_framework",
    "axes",
    "cloudinary",
    "jobs",
    "marketplace",
    "logistics",
    "users",
    "escrow",
    "chat",
    "notifications",
    "companies",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "axes.middleware.AxesMiddleware",
]
# Note : UpdateCacheMiddleware/FetchFromCacheMiddleware ("per-site cache") ont été retirés :
# ce pattern sert du contenu anonyme identique à tout le monde, et sur une API DRF authentifiée
# par JWT (pas par cookie de session), il rejouait la réponse mise en cache du premier utilisateur
# à tous les suivants sur la même URL — une fuite de données entre utilisateurs.

CORS_ALLOWED_ORIGINS = [
    origin for origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if origin
]

ROOT_URLCONF = "back_sentaa.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "back_sentaa.wsgi.application"
ASGI_APPLICATION = "back_sentaa.asgi.application"

# Redis : channel layer pour Channels (chat + suivi coursier temps réel).
# Réutilisé par CACHES (durcissement prod). Le broker/backend Celery ci-dessous utilise une
# DB Redis logique distincte (/2) sur la même instance pour ne pas mélanger les espaces de clés.
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [REDIS_URL]},
    }
}


CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL") or (
    REDIS_URL.rsplit("/", 1)[0] + "/2"
)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND") or CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

CELERY_BEAT_SCHEDULE = {
    "check-pending-escrow-payments": {
        "task": "notifications.tasks.check_pending_escrow_payments",
        "schedule": crontab(minute=0),  # toutes les heures
    },
    "check-pending-reception-confirmations": {
        "task": "notifications.tasks.check_pending_reception_confirmations",
        "schedule": crontab(hour=7, minute=0),  # 1x/jour, ~8h WAT (TIME_ZONE=UTC)
    },
    "check-pending-job-applications": {
        "task": "notifications.tasks.check_pending_job_applications",
        "schedule": crontab(hour=7, minute=30),  # 1x/jour, ~8h30 WAT
    },
    "send-weekly-newsletter": {
        "task": "notifications.tasks.send_weekly_newsletter",
        "schedule": crontab(hour=7, minute=0, day_of_week=1),  # lundi matin, ~8h WAT
    },
    # Réconciliation des reversements Mobile Money bloqués (BLOQUANT #12) : les transferts
    # sont asynchrones et sans webhook de statut → cette tâche interroge /transfers/{ref}.
    "reconcile-pending-payouts": {
        "task": "escrow.tasks.reconcile_pending_payouts",
        "schedule": crontab(minute="*/15"),  # tous les quarts d'heure
    },
}

# Seuils des rappels (notifications/tasks.py), ajustables sans redéploiement de code.
ESCROW_PENDING_REMINDER_HOURS = int(os.getenv("ESCROW_PENDING_REMINDER_HOURS", "24"))
RECEPTION_REMINDER_DAYS = int(os.getenv("RECEPTION_REMINDER_DAYS", "3"))
APPLICATION_REMINDER_DAYS = int(os.getenv("APPLICATION_REMINDER_DAYS", "5"))

# Réconciliation des reversements (escrow/tasks.py) : délai avant de considérer un transfert
# `pending` comme bloqué, et nombre max de re-vérifications avant escalade manuelle (borne le
# retry — pas de boucle infinie silencieuse).
PAYOUT_RECONCILIATION_MINUTES = int(os.getenv("PAYOUT_RECONCILIATION_MINUTES", "30"))
PAYOUT_RECONCILIATION_MAX_ATTEMPTS = int(
    os.getenv("PAYOUT_RECONCILIATION_MAX_ATTEMPTS", "5")
)

AUTH_USER_MODEL = "users.User"

# django-axes protège le formulaire de connexion Django admin (via authenticate()) contre le
# brute-force. Le flux OTP de l'API (custom, pas d'appel à authenticate()) est protégé séparément
# par le throttle scope 'otp' ci-dessous.
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]
AXES_FAILURE_LIMIT = int(os.getenv("AXES_FAILURE_LIMIT", "5"))
AXES_COOLOFF_TIME = int(os.getenv("AXES_COOLOFF_TIME", "1"))  # heures

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "otp": "5/min",
        "delivery_confirmation": "5/min",
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# JWT (SimpleJWT). Durées de vie explicites au lieu des défauts implicites :
# access court (limite la fenêtre d'un token volé), refresh plus long (confort).
# ROTATE_REFRESH_TOKENS : chaque refresh émet un nouveau refresh token ;
# BLACKLIST_AFTER_ROTATION blackliste l'ancien (nécessite l'app token_blacklist,
# ajoutée à INSTALLED_APPS) — un refresh token rejoué après rotation est refusé.
# Le logout (users/views.py::LogoutView) blackliste explicitement le refresh fourni.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASS"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
        "CONN_MAX_AGE": 60,
    }
}

JAZZMIN_SETTINGS = {
    # Titres et branding
    "site_title": "Senta'a Admin",
    "site_header": "Senta'a",
    "site_brand": "Senta'a Dashboard",
    "site_logo": "img/logo_sentaa.png",
    "login_logo": "img/logo_sentaa.png",
    "site_logo_classes": "img-circle elevation-3",
    "welcome_sign": "Bienvenue sur le portail Senta'a",
    "copyright": "Senta'a Ltd",
    "search_model": ["users.User", "marketplace.Listing"],
    "user_avatar": None,
    # Interface
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    # Icônes
    "icons": {
        "users.User": "fas fa-user-shield",
        "users.Group": "fas fa-users-cog",
        "marketplace.Listing": "fas fa-store",
        "escrow.Order": "fas fa-wallet",
        "jobs.JobOffer": "fas fa-briefcase",
        "auth": "fas fa-lock",
        "admin.LogEntry": "fas fa-history",
    },
    # Permet d'afficher/masquer le mot de passe
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
    # Amélioration des messages d'erreur
    # chemins mis à jour après réorganisation des fichiers statiques
    "custom_css": "css/admin_custom.css",
    "custom_js": "js/admin_custom.js",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode_theme": None,  # Désactive le thème sombre
    "default_theme_mode": "light",
    # Couleurs Senta'a
    "brand_colour": "navbar-white",  # Fond blanc pour le logo
    "accent": "accent-success",  # Vert pour les focus
    # Navbar : on passe en LIGHT
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    # Sidebar : on passe en LIGHT
    "sidebar": "sidebar-light-success",  # "light" au lieu de "dark"
    "sidebar_nav_child_indent": True,
    "sidebar_nav_flat_style": True,
    "theme_switcher": False,  # On cache le bouton lune/soleil
    "button_classes": {
        "primary": "btn-outline-primary",
        "success": "btn-success",
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SPECTACULAR_SETTINGS = {
    "TITLE": "Senta'a API",
    "DESCRIPTION": "Backend de la marketplace sécurisée Senta'a (Cameroun)",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_PATCH": True,
    "TAGS": [
        {"name": "Authentification", "description": "Gestion des comptes et OTP"},
    ],
}
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGES = [
    ("fr", "French"),
    ("en", "English"),
]

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Stockage média (images d'annonces, CV) : sur S3 si configuré, sinon disque local (dev).
# Sur Render, le disque est éphémère — sans S3, les fichiers uploadés sont perdus à chaque redeploy.
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
AWS_S3_ENDPOINT_URL = os.getenv(
    "AWS_S3_ENDPOINT_URL", ""
)  # pour un provider S3-compatible
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False

# django-jazzmin embarque un vendor bootstrap.bundle.min.js qui référence un .map absent du
# package. La variante "Manifest" de whitenoise resserre les références lors du collectstatic
# et échoue dessus ; la variante "Compressed" (sans hash de contenu, juste gzip/brotli) l'évite.
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
    "default": (
        {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"}
        if AWS_STORAGE_BUCKET_NAME
        else {"BACKEND": "django.core.files.storage.FileSystemStorage"}
    ),
}

# Cloudinary : stockage des IMAGES uniquement (logos entreprise, icônes catégorie, photos
# d'annonces, pièce d'identité coursier — voir les champs `CloudinaryField` dans
# users/marketplace/companies/models.py et la validation/URLs partagées dans common/images/).
# Les autres fichiers (CV en PDF, jobs.JobApplication.cv_file) restent sur le stockage
# ci-dessus (S3/local) : ce n'est pas de l'image, ça n'a pas sa place sur le plan gratuit
# Cloudinary dont le quota (25 crédits/mois) est déjà dimensionné pour les seules images.
# "cloudinary" dans INSTALLED_APPS ci-dessus est nécessaire pour que le SDK lise ce dict.
CLOUDINARY = {
    "cloud_name": os.getenv("CLOUDINARY_CLOUD_NAME", ""),
    "api_key": os.getenv("CLOUDINARY_API_KEY", ""),
    "api_secret": os.getenv("CLOUDINARY_API_SECRET", ""),
    "secure": True,
}
# Préfixe de dossier Cloudinary (organisation uniquement — le quota du plan gratuit est
# partagé par COMPTE, pas par dossier ; utiliser un compte distinct pour dev/staging si on
# veut vraiment isoler la consommation d'un environnement de test).
CLOUDINARY_FOLDER_PREFIX = os.getenv("CLOUDINARY_FOLDER_PREFIX", "sentaa")

# HTTPS / cookies sécurisés : uniquement en prod (DEBUG=False), sinon le dev local en HTTP casse.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )  # nécessaire derrière le proxy Render
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(
        os.getenv("SECURE_HSTS_SECONDS", 60 * 60 * 24 * 30)
    )  # 30 jours
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# NotchPay (agrégateur Mobile Money : MTN MoMo + Orange Money Cameroun)
NOTCHPAY_BASE_URL = os.getenv("NOTCHPAY_BASE_URL", "https://api.notchpay.co")
NOTCHPAY_PUBLIC_KEY = os.getenv("NOTCHPAY_PUBLIC_KEY", "")
NOTCHPAY_PRIVATE_KEY = os.getenv("NOTCHPAY_PRIVATE_KEY", "")
# « Webhook hash » NotchPay : secret HMAC-SHA256 vérifiant la signature `x-notch-signature`
# du webhook (escrow/views.py). Vide = pas de vérification de signature (dev/tests), la
# re-vérification via l'API reste la mitigation. Voir REFACTOR_PLAN.md (PR 5).
NOTCHPAY_WEBHOOK_HASH = os.getenv("NOTCHPAY_WEBHOOK_HASH", "")

# SMS OTP : "console" (défaut, log local, pas d'appel réseau — dev/tests) ou "twilio" (prod)
SMS_BACKEND = os.getenv("SMS_BACKEND", "console")
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.getenv("TWILIO_FROM_NUMBER", "")

# Email (rappels + newsletter, voir notifications/) : SMTP générique si EMAIL_HOST est
# renseigné, sinon backend "console" (log local, pas d'appel réseau — dev/tests).
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@senta-a.com")

# Domaine public du backend : sert à construire des URLs ABSOLUES dans les emails (logo
# statique, lien de désinscription newsletter) — un client mail ne connaît pas la même
# origine qu'un navigateur, `static()`/`reverse()` seuls ne renvoient qu'un chemin relatif.
# Doit rester cohérent avec ALLOWED_HOSTS (voir plus haut).
BACKEND_PUBLIC_URL = os.getenv(
    "BACKEND_PUBLIC_URL", "https://sentaaback.onrender.com"
).rstrip("/")

# Mention légale (pied de page email newsletter, anti-spam CAN-SPAM/RGPD — voir
# notifications/emails.py). Ville/pays uniquement : pas d'adresse postale précise disponible
# pour l'instant.
COMPANY_POSTAL_ADDRESS = os.getenv("COMPANY_POSTAL_ADDRESS", "Douala, Cameroun")

# Firebase Cloud Messaging (push notifications, voir notifications/) : contenu JSON complet
# du compte de service (PAS un chemin de fichier — volontaire, pour ne jamais avoir à déposer
# ce fichier sur le VPS), lu depuis l'environnement — jamais codé en dur, secret au même titre
# que les clés NotchPay ci-dessus (voir .claude/rules/push-notifications.md). Vide en
# dev/tests : notifications/services/push.py lève explicitement si un envoi est tenté sans
# credentials, plutôt que d'échouer silencieusement.
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "")

# Logging : sortie console structurée, lisible via `docker logs` / `docker compose logs`.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "standard"},
    },
    "root": {"handlers": ["console"], "level": os.getenv("DJANGO_LOG_LEVEL", "INFO")},
}
