# Generated by Django 5.0.14 on 2026-07-02 11:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("escrow", "0003_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="method",
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payout_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="channel",
            field=models.CharField(
                choices=[("cm.mtn", "MTN MoMo"), ("cm.orange", "Orange Money")],
                default="cm.mtn",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("successful", "Réussi"),
                    ("failed", "Échoué"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("collect", "Collecte (paiement acheteur)"),
                    ("withdraw", "Reversement (paiement vendeur)"),
                ],
                default="collect",
                max_length=10,
            ),
        ),
    ]
