# Generated by Django 5.0.14 on 2026-07-02 12:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("escrow", "0004_alter_paymenttransaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="destination_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="destination_latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="destination_longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
