# Generated by Django 5.0.14 on 2026-07-02 15:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("escrow", "0005_order_destination_label_order_destination_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="reception_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
