# Generated by Django 5.0.14 on 2026-07-05 17:57
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("escrow", "0006_order_payment_reminder_sent_at_and_more"),
        ("marketplace", "0003_listing_company_listingfavorite_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="marketplace.offer",
            ),
        ),
    ]
