# Generated by Django 5.0.14 on 2026-08-20 20:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0007_order_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("notchpay", "NotchPay"),
                    ("kpay", "KPay"),
                    ("moneyfusion", "MoneyFusion"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider_reference",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="channel",
            field=models.CharField(
                choices=[("mtn", "MTN MoMo"), ("orange", "Orange Money")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("collect", "Collecte (paiement acheteur)"),
                    ("withdraw", "Reversement (paiement vendeur)"),
                    ("courier_payout", "Reversement (paiement livreur)"),
                ],
                default="collect",
                max_length=20,
            ),
        ),
    ]
