# Generated by Django 5.0.14 on 2026-08-21 18:08
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0008_paymenttransaction_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="escrow.order",
            ),
        ),
    ]
