# Generated by Django 5.0.14 on 2026-08-21 19:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0009_paymenttransaction_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente de paiement"),
                    ("paid_escrow", "Payé (Fonds bloqués)"),
                    ("shipped", "Expédié"),
                    ("delivered", "Livré (En attente confirmation acheteur)"),
                    ("received", "Reçu (Validation acheteur)"),
                    ("completed", "Terminé (Fonds libérés)"),
                    ("disputed", "En litige"),
                    ("refunded", "Remboursé"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
