# Generated by Django 5.0.14 on 2026-08-23 20:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="reconciliation_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
