# Generated by Django 5.0.14 on 2026-09-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escrow", "0011_paymenttransaction_reconciliation_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="checkout_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_flow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("redirect", "Page hébergée (redirection)"),
                    ("ussd", "Push USSD direct"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "pending"), ("transaction_type", "collect")
                ),
                fields=("order",),
                name="unique_pending_collect_per_order",
            ),
        ),
    ]
